### ISSUE TITLE
비밀번호에 #이나 % 같은 특수문자가 있어서 나는 오류

### ISSUE THREAD

**Issue by ch-choi** [leegeunhyeok/cyworld-bot#16]
비밀번호에 특수문자(#, %)가 포함되어 있어 bot.py가 동작하지 않는 오류

Traceback (most recent call last):
  File "bot.py", line 273, in <module>
    user_password = config.get('user', 'password')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'

**Comment by leegeunhyeok** [comment]
현재 편리한 사용을 위해 GUI 개발 및 배포 작업을 진행하고 있습니다.

해당 작업이 마무리 되는대로 이슈 사항들을 하나씩 해결할 예정입니다.


빠른 시일 내에 해결할 수 있도록 하겠습니다.

**Comment by leegeunhyeok** [comment]
버전 업데이트 작업 시 함께 개선하도록 하겠습니다.

[참고](https://stackoverflow.com/questions/12603210/web-driver-skips-special-characters-and-characters-when-using-sendkeys)내용
